spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:6061/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:6062/
          predicates:
            - Path= /products/**
